
CREATE TABLE IF NOT EXISTS anime_characters (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  anime_id BIGINT UNSIGNED NOT NULL,
  name VARCHAR(128) NOT NULL,
  role VARCHAR(32) NOT NULL DEFAULT 'Supporting',
  image VARCHAR(1024),
  voice_actor VARCHAR(128),
  voice_actor_lang VARCHAR(32) DEFAULT 'Japanese',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS user_achievements (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  badge_key VARCHAR(64) NOT NULL,
  badge_name VARCHAR(128) NOT NULL,
  badge_icon VARCHAR(64) NOT NULL DEFAULT '🎖️',
  badge_color VARCHAR(32) DEFAULT '#D4AF37',
  description VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS watch_timestamps (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  anime_id BIGINT UNSIGNED NOT NULL,
  episode_id BIGINT UNSIGNED NOT NULL,
  timestamp INT UNSIGNED NOT NULL DEFAULT 0,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP
);
