CREATE TABLE IF NOT EXISTS user_follows (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  follower_id BIGINT UNSIGNED NOT NULL,
  following_id BIGINT UNSIGNED NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UNIQUE KEY unique_follow (follower_id, following_id)
);

CREATE TABLE IF NOT EXISTS user_activities (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  user_name VARCHAR(128) NOT NULL,
  type VARCHAR(32) NOT NULL,
  anime_id BIGINT UNSIGNED,
  anime_title VARCHAR(255),
  episode_number INT UNSIGNED,
  collection_id BIGINT UNSIGNED,
  content TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS watch_parties (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  room_code VARCHAR(8) NOT NULL UNIQUE,
  anime_id BIGINT UNSIGNED NOT NULL,
  episode_id BIGINT UNSIGNED NOT NULL,
  host_id BIGINT UNSIGNED NOT NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'waiting',
  `current_time` INT UNSIGNED NOT NULL DEFAULT 0,
  is_playing INT UNSIGNED NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS watch_party_participants (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  party_id BIGINT UNSIGNED NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  user_name VARCHAR(128) NOT NULL,
  joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS news_posts (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL UNIQUE,
  excerpt VARCHAR(500),
  content TEXT NOT NULL,
  cover_image VARCHAR(1024),
  category VARCHAR(32) NOT NULL DEFAULT 'news',
  author_name VARCHAR(128),
  views INT UNSIGNED NOT NULL DEFAULT 0,
  is_published INT UNSIGNED NOT NULL DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS manga_series (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  anime_id BIGINT UNSIGNED,
  title VARCHAR(255) NOT NULL,
  author VARCHAR(128),
  description TEXT,
  cover_image VARCHAR(1024),
  status VARCHAR(16) NOT NULL DEFAULT 'ongoing',
  total_chapters INT UNSIGNED NOT NULL DEFAULT 0,
  rating INT UNSIGNED,
  genres JSON,
  is_published INT UNSIGNED NOT NULL DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS manga_chapters (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  series_id BIGINT UNSIGNED NOT NULL,
  number INT UNSIGNED NOT NULL,
  title VARCHAR(255),
  pages JSON,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
