CREATE TABLE IF NOT EXISTS anime_requests (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  user_name VARCHAR(128) NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  genres JSON,
  year INT UNSIGNED,
  status VARCHAR(16) NOT NULL DEFAULT 'pending',
  votes INT UNSIGNED NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS request_votes (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  request_id BIGINT UNSIGNED NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UNIQUE KEY unique_vote (request_id, user_id)
);

CREATE TABLE IF NOT EXISTS bookmarks (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  anime_id BIGINT UNSIGNED NOT NULL,
  anime_title VARCHAR(255) NOT NULL,
  anime_image VARCHAR(1024),
  note VARCHAR(500),
  notify_new_episodes INT UNSIGNED NOT NULL DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS review_votes (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  review_id BIGINT UNSIGNED NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  is_helpful INT UNSIGNED NOT NULL DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS analytics_daily (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  date DATE NOT NULL UNIQUE,
  active_users INT UNSIGNED NOT NULL DEFAULT 0,
  new_users INT UNSIGNED NOT NULL DEFAULT 0,
  total_watch_time INT UNSIGNED NOT NULL DEFAULT 0,
  episodes_watched INT UNSIGNED NOT NULL DEFAULT 0,
  reviews_posted INT UNSIGNED NOT NULL DEFAULT 0,
  favorites_added INT UNSIGNED NOT NULL DEFAULT 0,
  page_views INT UNSIGNED NOT NULL DEFAULT 0
);
